package db2.ventana;

import db.dao.CarroDAOImpl;
import db.dao.DAOManager;
import db.dao.HoyoDAOImpl;
import db2.modelo.Carro;
import db2.modelo.Hoyo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

public class Ventana extends javax.swing.JFrame {

    static Ventana ventana;
    private static Lienzo lienzo;
    private DAOManager dAOManager;

    public Ventana() {
        initComponents();
        lienzo = new Lienzo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(515, 560));
        setPreferredSize(new java.awt.Dimension(515, 560));
        setResizable(false);

        jMenu1.setText("File");

        jMenuItem1.setText("Tamaño");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem3.setText("Ruta Taxi");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Rutas más costosas");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Ruta Costosa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator1);

        jMenuItem6.setText("Restablecer");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println(this.getSize());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        inicio();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        rutaCostosa();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dAOManager
     */
    public DAOManager getdAOManager() {
        return dAOManager;
    }

    /**
     * @param dAOManager the dAOManager to set
     */
    public void setdAOManager(DAOManager dAOManager) {
        this.dAOManager = dAOManager;
        Ventana.lienzo.setDao(dAOManager);
    }

    public void inicio() {
        lienzo.setBackground(new java.awt.Color(255, 255, 255));
        lienzo.setSize(500, 500);
        lienzo.setLocation(5, 5);
        Ventana.lienzo.pintarInicio();
        Ventana.lienzo.repaint();
        this.add(lienzo);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void rutaCostosa() {
        Ventana.lienzo.pintarRutaCostosa();
        Ventana.lienzo.repaint();
    }

    static class Lienzo extends JPanel {

        private List<Hoyo> huecos;
        private List<Carro> taxis;
        private DAOManager dao;
        Graphics2D our;

        public Lienzo() {
            this.huecos = new ArrayList<>();
            this.taxis = new ArrayList<>();
        }

        @Override
        public void paint(Graphics g) {
            super.paint(g); //To change body of generated methods, choose Tools | Templates.
            Graphics2D ourGraphics = (Graphics2D) g;
            if (!huecos.isEmpty()) {
                for (Hoyo hueco : huecos) {
                    int x1 = hueco.getX1();
                    int y1 = hueco.getY1();
                    int x2 = hueco.getX2();
                    int y2 = hueco.getY2();
                    int ancho = this.getWidth();
                    int alto = this.getHeight();
                    x1 *= (ancho / 100);
                    x2 *= (ancho / 100);
                    y1 *= (alto / 100);
                    y2 *= (alto / 100);
                    ourGraphics.fillRect(x1, y1, x2 - x1, y2 - y1);
                }
            }
            if (!taxis.isEmpty()) {
                for (Carro taxi : taxis) {
                    ourGraphics.setColor(Color.red);
                    ourGraphics.drawString("Dos circulos adicionales", 50, 50);
                    ourGraphics.drawOval(100, 100, 50, 50);
                    ourGraphics.drawOval(150, 150, 50, 50);
                }
            }

        }

        public void pintarRutaCostosa() {
            taxis.add(null);
        }

        public void pintarInicio() {
            HoyoDAOImpl hoyoDAOImpl = getDao().getHoyoDAOImpl();
            hoyoDAOImpl.iniciarTransaccion();
            CarroDAOImpl carroDAOImpl = getDao().getCarroDAOImpl();
            huecos = hoyoDAOImpl.listadoCompleto();
            taxis = carroDAOImpl.listar();
            hoyoDAOImpl.cerrarSession();
            carroDAOImpl.cerrarSession();
        }

        /**
         * @return the huecos
         */
        public List<Hoyo> getHuecos() {
            return huecos;
        }

        /**
         * @param huecos the huecos to set
         */
        public void setHuecos(List<Hoyo> huecos) {
            this.huecos = huecos;
        }

        /**
         * @return the taxis
         */
        public List<Carro> getTaxis() {
            return taxis;
        }

        /**
         * @param taxis the taxis to set
         */
        public void setTaxis(List<Carro> taxis) {
            this.taxis = taxis;
        }

        /**
         * @return the dao
         */
        public DAOManager getDao() {
            return dao;
        }

        /**
         * @param dao the dao to set
         */
        public void setDao(DAOManager dao) {
            this.dao = dao;
        }

    }
}
